com.tal.pricing_automation: # {group_id}.{name} from the knime.yml
  src: D:/git/knime_python_nodes # Path to folder containing the extension files
  conda_env_path: D:/git/knime_python_nodes/.pixi/envs/default # Path to the Python environment to use (use an absolute path)
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform
